/*
 * Analista.java
 *
 * Created on 19 de octubre de 2007, 17:23
 */

package cl.prien.encuestas;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Collections;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author  manuel
 */
public class Analista extends javax.swing.JFrame {
    private Connection c;
    private Hashtable<String,Field> columns;
    /** Creates new form Analista */
    public Analista()  {
        initComponents();
        progressBar.setVisible(false);
        this.setIconImage(new ImageIcon(getClass().getResource("/cl/prien/encuestas/icon.png")).getImage());
        
        c = Conexion.getConnection();
        columns = new Hashtable<String,Field>();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        frmOpenFile = new javax.swing.JFileChooser();
        frmSaveFile = new javax.swing.JFileChooser();
        frmSelectColumn = new javax.swing.JFrame();
        comboTable = new javax.swing.JComboBox();
        comboColumn = new javax.swing.JComboBox();
        btnAddColumn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPane = new javax.swing.JTextPane();
        btnExport = new javax.swing.JButton();
        btnRemoveColumn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboTipoVivienda = new javax.swing.JComboBox();
        frmAbout = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        mnuBar = new javax.swing.JMenuBar();
        mnuImportar = new javax.swing.JMenu();
        mnuAccess = new javax.swing.JMenuItem();
        mnuExportar = new javax.swing.JMenu();
        mnuExportAll = new javax.swing.JMenuItem();
        mnuExportSelect = new javax.swing.JMenuItem();
        mnuConfiguracion = new javax.swing.JMenu();
        mnuJDBC = new javax.swing.JMenuItem();
        mnuClean = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuAbout = new javax.swing.JMenuItem();

        frmOpenFile.setAcceptAllFileFilterUsed(false);
        frmOpenFile.setFileFilter(filtro());
        frmOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmOpenFileActionPerformed(evt);
            }
        });

        frmSaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmSaveFileActionPerformed(evt);
            }
        });

        comboTable.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTable.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTableItemStateChanged(evt);
            }
        });
        comboTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTableActionPerformed(evt);
            }
        });
        comboTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                comboTablePropertyChange(evt);
            }
        });

        comboColumn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAddColumn.setText("Agregar");
        btnAddColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddColumnActionPerformed(evt);
            }
        });

        txtPane.setEditable(false);
        jScrollPane1.setViewportView(txtPane);

        btnExport.setText("Exportar a Excel");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnRemoveColumn.setText("Eliminar");
        btnRemoveColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveColumnActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione las columnas que quiere incluir");

        jLabel3.setText("Tipo de Vivienda");

        comboTipoVivienda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTipoVivienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoViviendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmSelectColumnLayout = new javax.swing.GroupLayout(frmSelectColumn.getContentPane());
        frmSelectColumn.getContentPane().setLayout(frmSelectColumnLayout);
        frmSelectColumnLayout.setHorizontalGroup(
            frmSelectColumnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmSelectColumnLayout.createSequentialGroup()
                .addGroup(frmSelectColumnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmSelectColumnLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(btnExport))
                    .addGroup(frmSelectColumnLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(frmSelectColumnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(frmSelectColumnLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboTipoVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frmSelectColumnLayout.createSequentialGroup()
                                .addComponent(comboTable, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddColumn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveColumn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addGroup(frmSelectColumnLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        frmSelectColumnLayout.setVerticalGroup(
            frmSelectColumnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmSelectColumnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmSelectColumnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTipoVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmSelectColumnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddColumn)
                    .addComponent(btnRemoveColumn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExport)
                .addContainerGap())
        );
        frmAbout.setTitle("Analista Prien");
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/prien/encuestas/acerca_de.jpg")));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmAboutLayout = new javax.swing.GroupLayout(frmAbout.getContentPane());
        frmAbout.getContentPane().setLayout(frmAboutLayout);
        frmAboutLayout.setHorizontalGroup(
            frmAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        frmAboutLayout.setVerticalGroup(
            frmAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aprien");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/prien/encuestas/fondo.jpg")));

        progressBar.setMaximum(11);

        mnuImportar.setText("Importar");
        mnuImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuImportarActionPerformed(evt);
            }
        });

        mnuAccess.setText("Access");
        mnuAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAccessActionPerformed(evt);
            }
        });

        mnuImportar.add(mnuAccess);

        mnuBar.add(mnuImportar);

        mnuExportar.setText("Exportar");
        mnuExportAll.setText("todo");
        mnuExportAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExportAllActionPerformed(evt);
            }
        });

        mnuExportar.add(mnuExportAll);

        mnuExportSelect.setText("seleccionar Columnas");
        mnuExportSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExportSelectActionPerformed(evt);
            }
        });

        mnuExportar.add(mnuExportSelect);

        mnuBar.add(mnuExportar);

        mnuConfiguracion.setText("Configuraci\u00f3n");
        mnuConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConfiguracionActionPerformed(evt);
            }
        });

        mnuJDBC.setText("JDBC");
        mnuJDBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuJDBCActionPerformed(evt);
            }
        });

        mnuConfiguracion.add(mnuJDBC);

        mnuClean.setText("Limpiar registros hist\u00f3ricos");
        mnuClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCleanActionPerformed(evt);
            }
        });

        mnuConfiguracion.add(mnuClean);

        mnuBar.add(mnuConfiguracion);

        mnuHelp.setText("Ayuda");
        mnuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHelpActionPerformed(evt);
            }
        });

        mnuAbout.setText("Acerca de este software");
        mnuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutActionPerformed(evt);
            }
        });

        mnuHelp.add(mnuAbout);

        mnuBar.add(mnuHelp);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuImportarActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_mnuImportarActionPerformed
    
    private void comboTipoViviendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoViviendaActionPerformed
        if (comboTipoVivienda.getSelectedItem()==null)
            return;
        txtPane.setText("");
        columns = new Hashtable<String,Field>();
        
        
        String selected = comboTipoVivienda.getSelectedItem().toString();
        List<String> tables = null;
        if (selected.equals("Casa")){
            tables = (new Rules()).getTablesforCasa();
        } else {
            if (selected.equals("Departamento")){
                tables = (new Rules()).getTablesforDpto();
            }
        }
        comboTable.removeAllItems();
        for (String table: tables){
            comboTable.addItem(table);
        }
    }//GEN-LAST:event_comboTipoViviendaActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frmAbout.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void btnRemoveColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveColumnActionPerformed
        String key = comboTable.getSelectedItem() + ": " + comboColumn.getSelectedItem();
        String table = comboTable.getSelectedItem().toString();
        if (table.equals("Tabla_resumen_casas") || table.equals("Tabla_resumen_dpto"))
            table = "tablaresumen";
        List<String> rawnames = Conexion.getRawColumns(table);
        columns.remove(key);
        
        actualizarPanelColumnas();
    }//GEN-LAST:event_btnRemoveColumnActionPerformed
    
    private void mnuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutActionPerformed
        frmAbout.setVisible(true);
        frmAbout.setAlwaysOnTop(true);
        frmAbout.setSize(330,345);
        frmAbout.setIconImage(new ImageIcon(getClass().getResource("/cl/prien/encuestas/icon.png")).getImage());
        
    }//GEN-LAST:event_mnuAboutActionPerformed
    
    private void mnuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHelpActionPerformed
        
    }//GEN-LAST:event_mnuHelpActionPerformed
    
    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        frmSaveFile.showSaveDialog(this);
    }//GEN-LAST:event_btnExportActionPerformed
    
    private void btnAddColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddColumnActionPerformed
        String key = comboTable.getSelectedItem() + ": " + comboColumn.getSelectedItem();
        String table = comboTable.getSelectedItem().toString();
        if (table.equals("Tabla_resumen_casas") || table.equals("Tabla_resumen_dpto"))
            table = "tablaresumen";
        List<String> rawnames = Conexion.getRawColumns(table);
        columns.put(key,new Field(comboTable.getSelectedItem(),rawnames.get(comboColumn.getSelectedIndex()),comboColumn.getSelectedItem(),comboColumn.getSelectedIndex()));
        
        actualizarPanelColumnas();
        
    }//GEN-LAST:event_btnAddColumnActionPerformed
    
    private void actualizarPanelColumnas(){
        //pintar el panel de columnas elegidas
        String aux = "";
        Vector v = new Vector(columns.keySet());
        Collections.sort(v);
        Iterator it = v.iterator();
        while(it.hasNext()){
            aux += it.next() + "\n";
        }
        txtPane.setText(aux);
    }
    
    private void comboTableItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTableItemStateChanged
        
    }//GEN-LAST:event_comboTableItemStateChanged
    
    private void comboTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_comboTablePropertyChange
        
    }//GEN-LAST:event_comboTablePropertyChange
    
    private void comboTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTableActionPerformed
        if (comboTable.getSelectedItem()==null)
            return;
        String table = comboTable.getSelectedItem().toString();
        if (table.equals("Tabla_resumen_casas") || table.equals("Tabla_resumen_dpto"))
            table = "tablaresumen";
        comboColumn.removeAllItems();
        if (table==null || table.equals("Item 1"))
            return;
        System.out.println("ComboTable dice " + table);
        List<String> columnas = (new Rules()).getColumns(table);
        columnas.remove("id");
        
        for(String col: columnas){
            comboColumn.addItem(col);
        }
    }//GEN-LAST:event_comboTableActionPerformed
    
    private void mnuExportSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExportSelectActionPerformed
        frmSelectColumn.setVisible(true);
        frmSelectColumn.setSize(800,600);
        txtPane.setText("");
        comboTipoVivienda.removeAllItems();
        comboColumn.removeAllItems();
        comboTipoVivienda.addItem("Casa");
        comboTipoVivienda.addItem("Departamento");
        columns = new Hashtable<String,Field>();
        List<String> tables = (new Rules()).getTablesforCasa();
        comboTable.removeAllItems();
        for (String table: tables){
            comboTable.addItem(table);
        }
    }//GEN-LAST:event_mnuExportSelectActionPerformed
    
    private void mnuCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCleanActionPerformed
        List<String> tables = (new Rules()).getTables();
        tables.remove("Tabla_resumen_casas");
        tables.remove("Tabla_resumen_dpto");
        tables.add("registros");
        tables.add("tablaresumen");
        progressBar.setString("Limpiando tablas");
        progressBar.setValue(0);
        progressBar.setVisible(true);
        for(String table: tables){
            try {
                c.createStatement().execute("DELETE FROM " + table);
                progressBar.setValue(progressBar.getValue()+1);
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        progressBar.setVisible(false);
        
    }//GEN-LAST:event_mnuCleanActionPerformed
    
    private void mnuJDBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuJDBCActionPerformed
        Config n = new Config();
        n.setVisible(true);
    }//GEN-LAST:event_mnuJDBCActionPerformed
    
    private void mnuConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConfiguracionActionPerformed
        
        
    }//GEN-LAST:event_mnuConfiguracionActionPerformed
    
    private void frmSaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmSaveFileActionPerformed
        if (frmSaveFile.getSelectedFile() == null || evt.getActionCommand().equals("CancelSelection"))
            return;
        progressBar.setVisible(true);
        progressBar.setString("Exportando archivo");
        progressBar.setStringPainted(true);
        progressBar.setValue(0);
        Excel e = new Excel(frmSaveFile.getSelectedFile(),columns,progressBar);
        frmSelectColumn.setVisible(false);
        new Thread(e).start();
    }//GEN-LAST:event_frmSaveFileActionPerformed
    
    private void mnuExportAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExportAllActionPerformed
        columns = new Hashtable<String,Field>();
        frmSaveFile.showSaveDialog(this);
    }//GEN-LAST:event_mnuExportAllActionPerformed
    
    private void frmOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmOpenFileActionPerformed
        if (frmOpenFile.getSelectedFile() == null || evt.getActionCommand().equals("CancelSelection"))
            return;
        progressBar.setVisible(true);
        progressBar.setString("Importando archivo");
        progressBar.setStringPainted(true);
        progressBar.setValue(0);
        Importar i = new Importar(frmOpenFile.getSelectedFile().getAbsolutePath(),progressBar);
        new Thread(i).start();
    }//GEN-LAST:event_frmOpenFileActionPerformed
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //cerramos la conexion a la base de datos
        //Conexion.shutdown();
    }//GEN-LAST:event_formWindowClosing
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
// TODO: Agrege su codigo aqui:
    }//GEN-LAST:event_formWindowClosed
    
    private void mnuAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAccessActionPerformed
        frmOpenFile.showOpenDialog(this);
    }//GEN-LAST:event_mnuAccessActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analista().setVisible(true);
            }
        });
    }
    
    /**
     * Filtro para abrir solamente archivos Access con extension mdb
     * */
    private FileFilter filtro(){
        FileFilter filter = new FileFilter() {
            
            public boolean accept(File f) {
                if(f.isDirectory()) return true;
                if (f.getName().toLowerCase().endsWith(".mdb")) return true;
                return false;
            }
            
            public String getDescription() {
                return "Archivo de datos ACCESS (*.mdb)";
            }
        };
        return filter;
    }
    
    /**
     * Filtro para abrir exportar a archivos excel
     * */
    private FileFilter filtroExcel(){
        FileFilter filter = new FileFilter() {
            
            public boolean accept(File f) {
                if(f.isDirectory()) return true;
                if (f.getName().toLowerCase().endsWith(".xls")) return true;
                return false;
            }
            
            public String getDescription() {
                return "Hoja de Cálculos Excel";
            }
        };
        return filter;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddColumn;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnRemoveColumn;
    private javax.swing.JComboBox comboColumn;
    private javax.swing.JComboBox comboTable;
    private javax.swing.JComboBox comboTipoVivienda;
    private javax.swing.JFrame frmAbout;
    private javax.swing.JFileChooser frmOpenFile;
    private javax.swing.JFileChooser frmSaveFile;
    private javax.swing.JFrame frmSelectColumn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JMenuItem mnuAccess;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenuItem mnuClean;
    private javax.swing.JMenu mnuConfiguracion;
    private javax.swing.JMenuItem mnuExportAll;
    private javax.swing.JMenuItem mnuExportSelect;
    private javax.swing.JMenu mnuExportar;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuImportar;
    private javax.swing.JMenuItem mnuJDBC;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextPane txtPane;
    // End of variables declaration//GEN-END:variables
    
}
